# Generated by Django 5.2.4 on 2025-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('owner', 'Turf Owner')], default='user', max_length=20),
        ),
    ]
