# Generated by Django 5.2.4 on 2025-08-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking_updates',
            field=models.BooleanField(default=False),
        ),
    ]
