# Generated by Django 5.2.4 on 2025-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_booking_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_turfs_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
