# Generated by Django 5.2.4 on 2025-08-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_blocked_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
