# Generated by Django 5.2.4 on 2025-08-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_turf_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='turf',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
