# Generated by Django 5.2.4 on 2025-08-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_turf_status_alter_turf_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turf',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
