# Generated by Django 5.2.4 on 2025-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='turf_images/'),
        ),
    ]
