# Generated by Django 5.2.4 on 2025-08-22 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_turfimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='admin_warning_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WarningMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
