# Generated by Django 5.2.4 on 2025-08-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usermessage_delete_warningmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
