# Generated by Django 5.2.4 on 2025-08-22 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_comment_banned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_type',
            field=models.CharField(choices=[('warning', 'Warning'), ('info', 'Info'), ('update', 'Update'), ('report', 'Report')], default='info', max_length=20),
        ),
    ]
